[[pages]]
path = "streamlit_app.py"
name = "ホーム"
icon = ":house:"
[[pages]]
path = "./pages/page.py"
name = "助詞学習"
icon = ":one:"
[[pages]]
path = "./pages/page2.py"
name = "数え方学習"
icon = ":two:"
[[pages]]
path = "./pages/page3.py"
name = "丁寧語学習"
icon = ":three:"
